# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: symbol_manager/API/Protos/api.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'symbol_manager/API/Protos/api.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#symbol_manager/API/Protos/api.proto\x12\x03\x61pi\":\n\x06Symbol\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\"5\n\x11PostSymbolRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\"\x14\n\x12PostSymbolResponse\"\x13\n\x11GetSymbolsRequest\"2\n\x12GetSymbolsResponse\x12\x1c\n\x07symbols\x18\x01 \x03(\x0b\x32\x0b.api.Symbol\"\x19\n\x17GetActiveSymbolsRequest\"8\n\x18GetActiveSymbolsResponse\x12\x1c\n\x07symbols\x18\x01 \x03(\x0b\x32\x0b.api.Symbol\"/\n\x1dToggleSymbolActivationRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\" \n\x1eToggleSymbolActivationResponse2\xb7\x02\n\x03\x41pi\x12=\n\nPostSymbol\x12\x16.api.PostSymbolRequest\x1a\x17.api.PostSymbolResponse\x12=\n\nGetSymbols\x12\x16.api.GetSymbolsRequest\x1a\x17.api.GetSymbolsResponse\x12O\n\x10GetActiveSymbols\x12\x1c.api.GetActiveSymbolsRequest\x1a\x1d.api.GetActiveSymbolsResponse\x12\x61\n\x16ToggleSymbolActivation\x12\".api.ToggleSymbolActivationRequest\x1a#.api.ToggleSymbolActivationResponseB\x06\xaa\x02\x03\x41PIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'symbol_manager.API.Protos.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\003API'
  _globals['_SYMBOL']._serialized_start=44
  _globals['_SYMBOL']._serialized_end=102
  _globals['_POSTSYMBOLREQUEST']._serialized_start=104
  _globals['_POSTSYMBOLREQUEST']._serialized_end=157
  _globals['_POSTSYMBOLRESPONSE']._serialized_start=159
  _globals['_POSTSYMBOLRESPONSE']._serialized_end=179
  _globals['_GETSYMBOLSREQUEST']._serialized_start=181
  _globals['_GETSYMBOLSREQUEST']._serialized_end=200
  _globals['_GETSYMBOLSRESPONSE']._serialized_start=202
  _globals['_GETSYMBOLSRESPONSE']._serialized_end=252
  _globals['_GETACTIVESYMBOLSREQUEST']._serialized_start=254
  _globals['_GETACTIVESYMBOLSREQUEST']._serialized_end=279
  _globals['_GETACTIVESYMBOLSRESPONSE']._serialized_start=281
  _globals['_GETACTIVESYMBOLSRESPONSE']._serialized_end=337
  _globals['_TOGGLESYMBOLACTIVATIONREQUEST']._serialized_start=339
  _globals['_TOGGLESYMBOLACTIVATIONREQUEST']._serialized_end=386
  _globals['_TOGGLESYMBOLACTIVATIONRESPONSE']._serialized_start=388
  _globals['_TOGGLESYMBOLACTIVATIONRESPONSE']._serialized_end=420
  _globals['_API']._serialized_start=423
  _globals['_API']._serialized_end=734
# @@protoc_insertion_point(module_scope)
